### ISSUE TITLE
App crash in debug mode

### ISSUE THREAD

**Issue by luisfuertes** [SimenCodes/react-native-imei#15]
With debugger active app cant access to IMEI and crash. Without debug all works fine.

Error:
```
getDeviceId: Neither user 10701 nor current process has android.permission.READ_PHONE_STATE.
readException
Parcel.java:1943
```
(Is android 8, i request permission in componentDidMount and have permission added in manifest), but crash before load javascript code only in debug.

**Comment by askell** [comment]
It seems that it calls getConstants right after startup (even if there are no references to this module in JS code). So in new android permission model I have no chance to request required permissions

**Comment by Joao-Leite** [comment]
I'm having the same problem.
Did anyone find a workaround?

**Comment by askell** [comment]
For me it was simpler to implemented small java module and number of other files as described here https://facebook.github.io/react-native/docs/native-modules-android:
```
public class ImeiModule extends ReactContextBaseJavaModule {

    ReactApplicationContext reactContext;

    public ImeiModule(ReactApplicationContext reactContext) {
        super(reactContext);
        this.reactContext = reactContext;
    }

    @Override
    public String getName() {
        return "IMEIModule";
    }

    @ReactMethod
    public void getImei(Promise promise) {
        try {
            TelephonyManager tm = (TelephonyManager) this.reactContext.getSystemService(Context.TELEPHONY_SERVICE);
            String imei;
            if (android.os.Build.VERSION.SDK_INT >= 26) {
                imei = tm.getImei().trim();
            } else {
                imei = tm.getDeviceId();
            }
            promise.resolve(imei);
        } catch (SecurityException se) {
            promise.reject(se);
        }

    }
}
```
So I can use React Native PermissionsAndroid module to check and request permissions before calling getImei

**Comment by luisfuertes** [comment]
But app dont crash on `getImei()`, app crash only with `rn link`. I dont have import component in javascript code and app crash

**Comment by askell** [comment]
> But app doesnt crash on `getImei()`, app crash only with `rn link`. I dont have import component in javascript code and app crash

As I can see in stack trace, app is crashing because in debug mode (for some reason in some circumstances) it calls getConstants on startup. And if it has no permisisons for either getDeviceID/getImei (actually issue is reproduced only on one emulator of API v24 so it shows getDeviceId), it fails.
![screenshot_1551709918](https://user-images.githubusercontent.com/804611/53740221-501c7600-3ec6-11e9-86c2-42e6fff86a2a.png)
I had no time to investigate why it always calls getConstants in debug mode and just used code from getConstants of this module  in ReactMethod method above.

**Comment by luisfuertes** [comment]
@askell thanks for answer. 

If I have time I will try to investigate it

**Comment by Joao-Leite** [comment]
Could you tell me how you're passing the promisse in the getImei() method?
Thank you

**Comment by askell** [comment]
> Could you tell me how you're passing the promisse in the getImei() method?
> Thank you.
> 
> (Im running on an emulator with sdk 26 and it's also crashing on debug mode)

I created ImeiModule.js for convenience as recommended in documentation above:
```
import { NativeModules } from 'react-native';

const imeiModule = NativeModules.IMEIModule;

export default {
  getImei() {
    return imeiModule.getImei();
  }
};
```
and then call it as `const deviceImei = await ImeiModule.getImei();` So it looks like the promise is passed under the hood.

**Comment by Joao-Leite** [comment]
The following lines after the await aren't running, so I thought I had to pass something as the promise.

**Comment by askell** [comment]
> The following lines after the await aren't running, so I thought I had to pass something as the promise.

I guess you need to follow instructions in https://facebook.github.io/react-native/docs/native-modules-android carefully. There is a need to create an appropriate ReactPackage descendant and include it to MainApplication.java.

**Comment by Joao-Leite** [comment]
Thank you.
It looks like I hadn't wrapped the module properly.

Thanks for your help.

**Comment by luisfuertes** [comment]
with this code it seems fixed
```
    @Override
    public Map<String, Object> getConstants() {
       
        final Map<String, Object> constants = new HashMap<>();

        TelephonyManager tm = (TelephonyManager) this.reactContext.getSystemService(Context.TELEPHONY_SERVICE);
        if(tm == null || tm.getDeviceId() == null) {
            throw new RuntimeException("Failed to read tm (TelephonyManager is empty!)");
        }

        String imei = tm.getDeviceId().trim();
        if (imei.isEmpty()) {
            throw new RuntimeException("Failed to read IMEI (imei is empty!)");
        }
        constants.put("imei", imei);

        return constants;
    }
```

**Comment by askell** [comment]
> with this code it seems fixed
> 
I suppose that getConstants will not be re-evaluated if permission will be granted in the middle of application runtime (since Android M)

Is there any documentation for when getConstants method is getting invoked?

**Comment by biggeryan** [comment]
https://facebook.github.io/react-native/docs/permissionsandroid
maybe need do this first?

**Comment by askell** [comment]
> https://facebook.github.io/react-native/docs/permissionsandroid
> maybe need do this first?

No, you have no chance to do that because app fails at startup.

**Comment by SimenCodes** [comment]
I haven't been using the library myself since I wrote it back in 2016. Turns out PR #1 introduced more bugs than it solved, including this one. It seems getConstants is called at startup by the debugger if the app is running in debug mode, causing an exception you can't really catch. Next update will switch back to a promise-based implementation, hoping to get that up on NPM by next week.

**Comment by SimenCodes** [comment]
Version 0.2.0 is now available, and solves this issue. In order to fix it, I unfortunately had to break backwards compatibility.
