### ISSUE TITLE
Android resource linking failed during ./gradlew assembleRelease

### ISSUE THREAD

**Issue by myself379** [SimenCodes/react-native-imei#16]
`java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed`
`Output:  ..\node_modules\react-native-imei\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.`
`..\node_modules\react-native-imei\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.`
`..\node_modules\react-native-imei\android\build\intermediates\res\merged\release\values\values.xml:957: error: resource android:attr/fontVariationSettings not found.`
`..\node_modules\react-native-imei\android\build\intermediates\res\merged\release\values\values.xml:958: error: resource android:attr/ttcIndex not found.`
`error: failed linking references.`

I have this issue when attempt to ./gradlew assembleRelease

Can you guide me how to fix this issue?

**Comment by giggsoff** [comment]
You should modify file `node_modules\react-native-imei\android\build.gradle` to the following:

```
apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 26)
        versionCode 2
        versionName "1.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    compile 'com.facebook.react:react-native:+'
}
```

**Comment by SimenCodes** [comment]
Reopen if issue is still present in version 0.2.0 of this library :)
