### ISSUE TITLE
Error: Missing permission android.permission.READ_PHONE_STATE

### ISSUE THREAD

**Issue by ishareme** [SimenCodes/react-native-imei#19]
Do not manually open permissions to resolve， how to deal with it

**Comment by SimenCodes** [comment]
Please provide more info about your problem and then reopen the issue.

**Comment by ishareme** [comment]
open

**Comment by ishareme** [comment]
re-open #19

**Comment by ishareme** [comment]
![image](https://user-images.githubusercontent.com/25175055/65490373-9cb9b400-dedf-11e9-840b-2a3d9d33edc0.png)

Permissions have been added


![image](https://user-images.githubusercontent.com/25175055/65490317-84499980-dedf-11e9-9ad5-8a297ebab854.png)

But still prompted no permission

**Comment by SimenCodes** [comment]
Please read the react native guide on how to request permissions again.
https://nb.lmgtfy.com/?s=d&q=react%20native%20android%20permission%20guide
