### ISSUE TITLE
Neither user 10084 nor current process has android.permission.READ_PHONE_STATE

### ISSUE THREAD

**Issue by NgKhanh** [SimenCodes/react-native-imei#5]
I got this issue in debug mode on Android simulator
```
Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
getConstants
    RNImeiModule.java:31
getConstants
    JavaModuleWrapper.java:140
run
    NativeRunnable.java
handleCallback
    Handler.java:790
.....
```

**Comment by SimenCodes** [comment]
Hi!

You get that error only if you haven't granted the right permission. Check
the documentation for the permission library you are using to find the
correct string that corresponds to this permission. Also, check under
advanced permission settings on the device that you have declared the
permission correctly.

Den fre. 8. des. 2017, 08:07 skrev Thank <notifications@github.com>:

**Comment by sarykemmoun** [comment]
Hello, 
I get this error message too, But only when the debugger is on.
I added the permission as described in the documentation. 
I can't use the app w/o debugging.

Do you have any idea why does it happen?

**Comment by SimenCodes** [comment]
Didn't hear anything, guessing that it works now. So closing.

**Comment by merigold** [comment]
I have the same problem.  When run in debug mode I have error. I must first only run app, then grant permission and next can run in debug mode.

**Comment by Manoj002** [comment]
Android app is crashing in productiuon build.... same errorrrr
