### ISSUE TITLE
Please document why iOS is not supported

### ISSUE THREAD

**Issue by JonasDralle** [SimenCodes/react-native-imei#6]
iOS doesn't allow to programatically read out the IMEI.
https://stackoverflow.com/a/19927376

this isn't comprehensible from the README. In fact iOS wasn't even mentioned.

**Comment by JonasDralle** [comment]
expect my PR

**Comment by SimenCodes** [comment]
Thanks for the text update! Always useful with better explanations why something only works on some platforms.
