### ISSUE TITLE
CDMA or ESN returns MEID 

### ISSUE THREAD

**Issue by lilei-1** [SimenCodes/react-native-imei#8]
Please use `TelephonyManager.getImei()` instead of `TelephoneyManager.getDeviceId()`.

**Comment by SimenCodes** [comment]
Thanks for the heads-up! I don't have time to fix this in the near future, so pull requests addressing this are welcome.

**Comment by SimenCodes** [comment]
Reopening, as this should be fixed at some point once someone has the time do it properly

**Comment by SimenCodes** [comment]
Fixed in #11
